//Music

audio_sound_gain(mus_Lace, global.musicVolume/100,0);
audio_sound_gain(mus_TakeOver, global.musicVolume/100,0);
audio_sound_gain(mus_BloodyDestiny, global.musicVolume/100,0);
audio_sound_gain(mus_CaptureTheTarget, global.musicVolume/100,0);
audio_sound_gain(mus_Overworld1, global.musicVolume/100,0);
audio_sound_gain(mus_Overworld2, global.musicVolume/100,0);
audio_sound_gain(mus_Overworld3, global.musicVolume/100,0);
audio_sound_gain(mus_MistyRain, global.musicVolume/100,0);
audio_sound_gain(mus_Dreams, global.musicVolume/100,0);
audio_sound_gain(mus_HulkHogan, global.musicVolume/100,0);
audio_sound_gain(mus_Title, global.musicVolume/100,0);
audio_sound_gain(mus_TitleAlt, global.musicVolume/100,0);
audio_sound_gain(mus_IntroStatic, global.musicVolume/100,0);

//Sound Effects

audio_sound_gain(snd_Guns_Pistol, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_Bark, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_Knife, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_RoadRoller, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_Reload_Normal, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_Reload_Sword, global.sfxVolume/100,0);
audio_sound_gain(snd_Guns_Reload_Bark, global.sfxVolume/100,0);
audio_sound_gain(snd_RobotHit, global.sfxVolume/100,0);
audio_sound_gain(snd_YouDied, global.sfxVolume/100,0);
audio_sound_gain(snd_GameOverYeah, global.sfxVolume/100,0);
audio_sound_gain(snd_RonaldinhoSoccer, global.sfxVolume/100,0);
audio_sound_gain(snd_WallHit, global.sfxVolume/100,0);
audio_sound_gain(snd_GemHit, global.sfxVolume/100,0);
audio_sound_gain(snd_EnemyDie, global.sfxVolume/100,0);
audio_sound_gain(snd_DoorKnock, global.sfxVolume/100,0);
audio_sound_gain(snd_DoorOpen, global.sfxVolume/100,0);
audio_sound_gain(snd_Typewriter, global.sfxVolume/100,0);
audio_sound_gain(snd_MenuSelect, global.sfxVolume/100,0);
audio_sound_gain(snd_ButtonNo, global.sfxVolume/100,0);
audio_sound_gain(snd_ButtonYes, global.sfxVolume/100,0);
audio_sound_gain(snd_Fazcoin, global.sfxVolume/100,0);
audio_sound_gain(snd_BurningMemoryShort, global.sfxVolume/100,0);
audio_sound_gain(snd_BurningMemory, global.sfxVolume/100,0);

//Dialogue

audio_sound_gain(snd_Freddy_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_Freddy_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_Freddy_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_Bonnie_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_Bonnie_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_Bonnie_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_Chica_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_Chica_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_Chica_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene1, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene2, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene3, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene4, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene5, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene6, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene7, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene8, global.dialogueVolume/100,0);
audio_sound_gain(snd_Fredbear_Cutscene9, global.dialogueVolume/100,0);
audio_sound_gain(snd_BalloonBoy_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalFreddy_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalFreddy_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalFreddy_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalBonnie_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalBonnie_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalBonnie_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalChica_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalChica_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_MetalChica_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_AnnoyingDog_Gameplay1, global.dialogueVolume/100,0);
audio_sound_gain(snd_AnnoyingDog_Gameplay2, global.dialogueVolume/100,0);
audio_sound_gain(snd_AnnoyingDog_Gameplay3, global.dialogueVolume/100,0);
audio_sound_gain(snd_AnnoyingDog_Hurt, global.dialogueVolume/100,0);
audio_sound_gain(snd_AnnoyingDog_Death, global.dialogueVolume/100,0);
audio_sound_gain(snd_HulkHogan_Cutscene1, global.dialogueVolume/100,0);
audio_sound_gain(snd_HulkHogan_Cutscene2, global.dialogueVolume/100,0);
